language: python
sudo: enabled
services:
  - mysql
matrix:
  include:
    - name: "Python 3.5 on Xenial Linux"
      python: 3.5
      dist: xenial
      before_install:
        - pip install PyMySQL
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
      dist: xenial
      before_install:
        - pip install PyMySQL
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
      dist: xenial
      before_install:
        - pip install PyMySQL
addons:
  apt:
    packages:
    - git
    - openssl
    - curl
    - nginx
    - dos2unix
  homebrew:
    packages:
    - git
    - openssl
    - curl
    - nginx
    - dos2unix
install:
  - pip install -r requirements.txt
script:
  - java -version
  - cd deploy
  - sed -i "s%dbUsername%root%g" common.properties
  - sed -i "s%dbPassword%%g" common.properties
  - python3 deploy.py installAll travis && python telnet.py
